sonar.projectKey=ohmyopensource_ohmyuniversity-web
sonar.organization=ohmyopensource
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Sources
sonar.sources=src
sonar.tests=src

# Inclusions
sonar.test.inclusions=**/*.spec.ts

# Exclusions
sonar.exclusions=**/*.spec.ts,src/main.ts,src/environments/**

sonar.coverage.exclusions=src/main.ts,src/environments/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json
