/**
 * @file custom-badge.component.ts
 * @description Reusable badge component supporting semantic variants,
 * sizes, icons, counters, removable actions, and status indicators.
 */

import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideDynamicIcon, LucideX } from '@lucide/angular';

export type BadgeVariant =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'success'
  | 'warning'
  | 'error'
  | 'info'
  | 'ghost'
  | 'outline'
  | 'flat'
  | 'neutral';

export type BadgeSize = 'xs' | 'sm' | 'md' | 'lg';

/**
 * Defines the badge border style.
 */
export type BadgeShape = 'pill' | 'rounded' | 'square';

export type IconPosition = 'left' | 'right';

/**
 * Displays a compact badge used for status indication, counters,
 * labels, and removable tags.
 */
@Component({
  selector: 'app-custom-badge',
  standalone: true,
  imports: [CommonModule, LucideDynamicIcon],
  templateUrl: './custom-badge.component.html',
  styleUrls: ['./custom-badge.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CustomBadgeComponent {
  /** Internal icon used by removable badges. */
  readonly closeIcon = LucideX;

  /**
   * Badge label.
   */
  @Input() label: string = '';

  /**
   * Numeric counter displayed instead of the label when greater than zero.
   */
  @Input() count: number = 0;

  /**
   * Maximum counter value before displaying a capped representation.
   */
  @Input() maxCount: number = 99;

  /**
   * Visual variant applied to the badge.
   */
  @Input() variant: BadgeVariant = 'primary';

  /**
   * Badge size.
   */
  @Input() size: BadgeSize = 'md';

  /**
   * Badge shape.
   */
  @Input() shape: BadgeShape = 'pill';

  /**
   * Enables dark theme styling.
   */
  @Input() darkTheme: boolean = false;

  /**
   * Optional Lucide icon displayed inside the badge.
   */
  @Input() icon: any = null;

  /**
   * Position of the icon relative to the content.
   */
  @Input() iconPosition: IconPosition = 'left';

  /**
   * Displays the badge as a status dot without textual content.
   */
  @Input() dot: boolean = false;

  // ── Comportamento ─────────────────────────────────────────────────────────

  /**
   * Enables badge removal through a dedicated action button.
   */
  @Input() removable: boolean = false;

  /**
   * Accessible label announced by screen readers.
   */
  @Input() ariaLabel: string = '';

  /**
   * Emitted when the remove action is triggered.
   */
  @Output() removed = new EventEmitter<void>();

  /**
   * Returns the icon size associated with the current badge size.
   */
  get iconSize(): number {
    const map: Record<BadgeSize, number> = { xs: 10, sm: 11, md: 12, lg: 14 };
    return map[this.size];
  }

  /**
   * Returns the remove icon size associated with the current badge size.
   */
  get closeSize(): number {
    const map: Record<BadgeSize, number> = { xs: 9, sm: 10, md: 11, lg: 12 };
    return map[this.size];
  }

  /**
   * Returns the formatted counter value.
   */
  get displayCount(): string {
    return this.count > this.maxCount ? `${this.maxCount}+` : `${this.count}`;
  }

  /**
   * Indicates whether the badge is displaying a counter.
   */
  get isCountMode(): boolean {
    return this.count > 0;
  }

  /**
   * Indicates whether the badge is rendered as a standalone status dot.
   */
  get isDotOnly(): boolean {
    return this.dot && !this.label && !this.isCountMode;
  }

  /**
   * Returns the CSS classes required for the current badge configuration.
   */
  get badgeClasses(): Record<string, boolean> {
    return {
      badge: true,
      [`badge--${this.variant}`]: true,
      [`badge--${this.size}`]: true,
      [`badge--${this.shape}`]: true,
      'badge--dark': this.darkTheme,
      'badge--dot-only': this.isDotOnly,
      'badge--count': this.isCountMode && !this.dot,
      'badge--removable': this.removable,
      'badge--icon-right': this.icon !== null && this.iconPosition === 'right',
    };
  }

  /**
   * Handles the badge removal action.
   *
   * @param event Mouse event generated by the remove button.
   */
  onRemove(event: MouseEvent): void {
    event.stopPropagation();
    this.removed.emit();
  }
}
