import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { AuthRepository } from './features/auth/domain/repositories/auth.repository';
import { AuthApiRepository } from './features/auth/infrastructure/api/auth-api.repository';
import { AuthFacade } from './features/auth/application/facades/auth.facade';
import { LoginUseCase } from './features/auth/application/usecases/login.usecase';
import { LogoutUseCase } from './features/auth/application/usecases/logout.usecase';
import { RefreshTokenUseCase } from './features/auth/application/usecases/refresh-token.usecase';
import {
  provideLucideIcons,
  LucideLayoutDashboard,
  LucideGraduationCap,
  LucideCalendarDays,
  LucideFilePenLine,
  LucideFolderOpen,
  LucideBadgeEuro,
  LucideBriefcase,
  LucideMessageSquare,
  LucideCompass,
  LucideSettings,
  LucideCircleUser,
  LucideLogOut,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucideBell,
  LucideChevronUp,
  LucideX,
  LucideLoaderCircle,
  LucideDownload,
  LucideArrowRight,
  LucideTrash2,
  LucideCircleCheck,
  LucideHeart,
  LucideStar,
  LucideSearch,
  LucideShare2,
  LucidePlus,
  LucideShield,
  LucideTriangleAlert,
  LucideCircleX,
  LucideInfo,
  LucideTag,
  LucideFlame,
  LucideClock,
  LucideWifi,
  LucideFunnel,
  LucideSend,
  LucidePaperclip,
  LucideFile,
  LucideLink,
  LucideUsers,
  LucideArrowLeft,
  LucideChevronRight,
  LucideUser,
  LucideMail,
  LucidePhone,
  LucideMapPin,
  LucideCalendar,
  LucidePencil,
  LucideBookOpen,
  LucideAward,
  LucideKey,
  LucideCamera,
  LucideExternalLink,
  LucideBuilding2,
  LucideMap,
  LucideCalendarPlus,
  LucideLayers,
  LucideMonitor,
  LucideZap,
  LucideWallet,
  LucideCalendarCheck,
  LucideCalendarX,
  LucideClipboardList,
  LucideClipboardCheck,
  LucideHeadphones,
  LucideMegaphone,
  LucideCreditCard,
  LucideCircleAlert,
  LucideEuro,
  LucideBookMarked,
  LucideThumbsUp,
  LucideSun,
  LucideSparkles,
  LucideCalculator,
  LucideHourglass,
} from '@lucide/angular';
import { CarrieraFacade } from './features/dashboard/application/facades/carriera.facade';
import { GetTasseUseCase } from './features/dashboard/application/usecases/get-tasse.usecase';
import { CarrieraRepository } from './features/dashboard/domain/repositories/carriera.repository';
import { CarrieraApiRepository } from './features/dashboard/infrastructure/api/carriera-api.repository';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withInterceptors([authInterceptor])),

    // Auth
    { provide: AuthRepository, useClass: AuthApiRepository },
    { provide: CarrieraRepository, useClass: CarrieraApiRepository },
    AuthFacade,
    LoginUseCase,
    LogoutUseCase,
    RefreshTokenUseCase,
    CarrieraFacade,
    GetTasseUseCase,

    provideLucideIcons(
      LucideLayoutDashboard,
      LucideGraduationCap,
      LucideCalendarDays,
      LucideFilePenLine,
      LucideFolderOpen,
      LucideBadgeEuro,
      LucideBriefcase,
      LucideMessageSquare,
      LucideCompass,
      LucideSettings,
      LucideCircleUser,
      LucideLogOut,
      LucidePanelLeftClose,
      LucidePanelLeftOpen,
      LucideBell,
      LucideChevronUp,
      LucideX,
      LucideLoaderCircle,
      LucideDownload,
      LucideArrowRight,
      LucideTrash2,
      LucideCircleCheck,
      LucideHeart,
      LucideStar,
      LucideSearch,
      LucideShare2,
      LucidePlus,
      LucideShield,
      LucideTriangleAlert,
      LucideCircleX,
      LucideInfo,
      LucideTag,
      LucideFlame,
      LucideClock,
      LucideWifi,
      LucideFunnel,
      LucideSend,
      LucidePaperclip,
      LucideFile,
      LucideLink,
      LucideUsers,
      LucideArrowLeft,
      LucideChevronRight,
      LucideUser,
      LucideMail,
      LucidePhone,
      LucideMapPin,
      LucideCalendar,
      LucidePencil,
      LucideBookOpen,
      LucideAward,
      LucideKey,
      LucideCamera,
      LucideExternalLink,
      LucideBuilding2,
      LucideMap,
      LucideCalendarPlus,
      LucideLayers,
      LucideMonitor,
      LucideZap,
      LucideWallet,
      LucideCalendarCheck,
      LucideCalendarX,
      LucideClipboardList,
      LucideClipboardCheck,
      LucideHeadphones,
      LucideMegaphone,
      LucideCreditCard,
      LucideCircleAlert,
      LucideEuro,
      LucideBookMarked,
      LucideThumbsUp,
      LucideSun,
      LucideSparkles,
      LucideCalculator,
      LucideHourglass,
    ),
  ],
};
