import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { routes } from './app.routes';
import {
  provideLucideIcons,
  LucideLayoutDashboard,
  LucideGraduationCap,
  LucideCalendarDays,
  LucideFilePenLine,
  LucideFolderOpen,
  LucideBadgeEuro,
  LucideBriefcase,
  LucideMessageSquare,
  LucideCompass,
  LucideSettings,
  LucideCircleUser,
  LucideLogOut,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucideBell,
  LucideChevronUp,
  LucideX,
  LucideLoaderCircle,
  LucideDownload,
  LucideArrowRight,
  LucideTrash2,
  LucideCircleCheck,
  LucideHeart,
  LucideStar,
  LucideSearch,
  LucideShare2,
  LucidePlus,
  LucideShield,
  LucideTriangleAlert,
  LucideCircleX,
  LucideInfo,
  LucideTag,
  LucideFlame,
  LucideClock,
  LucideWifi,
  LucideFunnel,
} from '@lucide/angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideLucideIcons(
      LucideLayoutDashboard,
      LucideGraduationCap,
      LucideCalendarDays,
      LucideFilePenLine,
      LucideFolderOpen,
      LucideBadgeEuro,
      LucideBriefcase,
      LucideMessageSquare,
      LucideCompass,
      LucideSettings,
      LucideCircleUser,
      LucideLogOut,
      LucidePanelLeftClose,
      LucidePanelLeftOpen,
      LucideBell,
      LucideChevronUp,
      LucideX,
      LucideLoaderCircle,
      LucideDownload,
      LucideArrowRight,
      LucideTrash2,
      LucideCircleCheck,
      LucideHeart,
      LucideStar,
      LucideSearch,
      LucideShare2,
      LucidePlus,
      LucideShield,
      LucideTriangleAlert,
      LucideCircleX,
      LucideInfo,
      LucideTag,
      LucideFlame,
      LucideClock,
      LucideWifi,
      LucideFunnel,
    ),
  ],
};
