import { University } from '@shared/types';

/**
 * Comprehensive list of Italian universities (statali, private, telematiche).
 *
 * emailDomains are derived from each university's CINECA/Esse3 slug where
 * available, since in most cases the institutional email domain matches it
 * (e.g. unimol.esse3.cineca.it → @studenti.unimol.it / @unimol.it).
 * This is a reasonable default, NOT a verified guarantee for every entry,
 * universities marked with an empty emailDomains array had no slug source
 * available and need manual verification before being usable for login
 * validation.
 */
export const UNIVERSITIES: University[] = [
  // Public Universities
  {
    id: 'casd',
    name: 'Centro Alti Studi per la Difesa',
    shortName: 'CASD',
    emailDomains: ['casd.difesa.it'],
    city: 'Roma',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'iusspavia',
    name: 'Istituto Universitario di Studi Superiori di Pavia',
    shortName: 'IUSS Pavia',
    emailDomains: ['iusspavia.it'],
    city: 'Pavia',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'poliba',
    name: 'Politecnico di Bari',
    shortName: 'Poliba',
    emailDomains: ['poliba.it'],
    city: 'Bari',
    type: 'statale',
    campuses: [
      {
        id: 'poliba-bari',
        name: 'Campus di Bari',
        city: 'Bari',
        address: 'Via Orabona 4, 70125 Bari',
      },
      {
        id: 'poliba-taranto',
        name: 'Centro Interdipartimentale Magna Grecia - Taranto',
        city: 'Taranto',
        address: 'Viale del Turismo 10, 74123 Taranto',
      },
      {
        id: 'poliba-foggia',
        name: 'Polo didattico di Foggia',
        city: 'Foggia',
        address: 'Piazzale Puglia 10, 71121 Foggia',
      },
    ],
  },
  {
    id: 'polimi',
    name: 'Politecnico di Milano',
    shortName: 'PoliMi',
    emailDomains: ['polimi.it'],
    city: 'Milano',
    type: 'statale',
    campuses: [
      {
        id: 'polimi-leonardo',
        name: 'Campus Leonardo',
        city: 'Milano',
        address: 'Piazza Leonardo da Vinci 32, 20133 Milano',
      },
      {
        id: 'polimi-bovisa',
        name: 'Campus Bovisa',
        city: 'Milano',
        address: 'Via Giuseppe La Masa 1, 20156 Milano',
      },
      { id: 'polimi-cremona', name: 'Polo territoriale di Cremona', city: 'Cremona' },
      {
        id: 'polimi-lecco',
        name: 'Polo territoriale di Lecco',
        city: 'Lecco',
        address: 'Via Gaetano Previati 1/c, 23900 Lecco',
      },
      {
        id: 'polimi-mantova',
        name: 'Polo territoriale di Mantova',
        city: 'Mantova',
        address: "Piazza d'Arco 3, 46100 Mantova",
      },
      { id: 'polimi-piacenza', name: 'Polo territoriale di Piacenza', city: 'Piacenza' },
    ],
  },
  {
    id: 'polito',
    name: 'Politecnico di Torino',
    shortName: 'PoliTo',
    emailDomains: ['polito.it'],
    city: 'Torino',
    type: 'statale',
    campuses: [
      {
        id: 'polito-cittadella',
        name: 'Cittadella Politecnica',
        city: 'Torino',
        address: 'Corso Duca degli Abruzzi 24, 10129 Torino',
      },
      {
        id: 'polito-valentino',
        name: 'Castello del Valentino',
        city: 'Torino',
        address: 'Viale Pier Andrea Mattioli 39, 10125 Torino',
      },
      {
        id: 'polito-lingotto',
        name: 'Sede Lingotto',
        city: 'Torino',
        address: 'Via Nizza 230, 10126 Torino',
      },
    ],
  },
  {
    id: 'imtlucca',
    name: 'Scuola IMT Alti Studi di Lucca',
    shortName: 'IMT Lucca',
    emailDomains: ['imtlucca.it'],
    city: 'Lucca',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'sissa',
    name: 'Scuola Internazionale Superiore di Studi Avanzati di Trieste',
    shortName: 'SISSA',
    emailDomains: ['sissa.it'],
    city: 'Trieste',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'sns',
    name: 'Scuola Normale Superiore di Pisa',
    shortName: 'Normale Pisa',
    emailDomains: ['sns.it'],
    city: 'Pisa',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'ssm',
    name: 'Scuola Superiore Meridionale di Napoli',
    shortName: 'SSM Napoli',
    emailDomains: ['ssm.unina.it'],
    city: 'Napoli',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'sssup',
    name: "Scuola Superiore Sant'Anna di Pisa",
    shortName: "Sant'Anna Pisa",
    emailDomains: ['santannapisa.it'],
    city: 'Pisa',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unive',
    name: "Università Ca' Foscari Venezia",
    shortName: "Ca' Foscari",
    emailDomains: ['unive.it'],
    city: 'Venezia',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'uniurb',
    name: 'Università degli Studi "Carlo Bo" di Urbino',
    shortName: 'UniUrb',
    emailDomains: ['uniurb.it'],
    city: 'Urbino',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'univpm',
    name: 'Università Politecnica delle Marche',
    shortName: 'UnivPM',
    emailDomains: ['univpm.it'],
    city: 'Ancona',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'uniba',
    name: 'Università degli Studi di Bari',
    shortName: 'UniBa',
    emailDomains: ['uniba.it'],
    city: 'Bari',
    type: 'statale',
    campuses: [
      {
        id: 'uniba-bari',
        name: 'Sede di Bari',
        city: 'Bari',
        address: 'Piazza Umberto I 1, 70121 Bari',
      },
      { id: 'uniba-taranto', name: 'Dipartimento Jonico - Taranto', city: 'Taranto' },
      { id: 'uniba-brindisi', name: 'Sede di Brindisi', city: 'Brindisi' },
    ],
  },
  {
    id: 'unibg',
    name: 'Università degli Studi di Bergamo',
    shortName: 'UniBg',
    emailDomains: ['unibg.it'],
    city: 'Bergamo',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unibo',
    name: 'Università degli Studi di Bologna',
    shortName: 'UniBo',
    emailDomains: ['unibo.it', 'studio.unibo.it'],
    city: 'Bologna',
    type: 'statale',
    campuses: [
      {
        id: 'unibo-bologna',
        name: 'Sede di Bologna',
        city: 'Bologna',
        address: 'Via Zamboni 33, 40126 Bologna',
      },
      {
        id: 'unibo-cesena',
        name: 'Campus di Cesena',
        city: 'Cesena',
        address: "Via dell'Università, 47521 Cesena",
      },
      {
        id: 'unibo-forli',
        name: 'Campus di Forlì',
        city: 'Forlì',
        address: 'Corso della Repubblica, 47121 Forlì',
      },
      {
        id: 'unibo-ravenna',
        name: 'Campus di Ravenna',
        city: 'Ravenna',
        address: 'Via Baccarini 27, 48121 Ravenna',
      },
      { id: 'unibo-rimini', name: 'Campus di Rimini', city: 'Rimini' },
    ],
  },
  {
    id: 'unibs',
    name: 'Università degli Studi di Brescia',
    shortName: 'UniBs',
    emailDomains: ['unibs.it'],
    city: 'Brescia',
    type: 'statale',
    campuses: [
      {
        id: 'unibs-centro',
        name: 'Sede centrale - Piazza del Mercato',
        city: 'Brescia',
        address: 'Piazza del Mercato 15, 25121 Brescia',
      },
      {
        id: 'unibs-sanfaustino',
        name: 'San Faustino (Economia, Giurisprudenza)',
        city: 'Brescia',
        address: 'Via San Faustino 74/B, 25122 Brescia',
      },
      {
        id: 'unibs-nord',
        name: 'Campus Nord (Medicina, Ingegneria)',
        city: 'Brescia',
        address: 'Viale Europa 11, 25123 Brescia',
      },
    ],
  },
  {
    id: 'unica',
    name: 'Università degli Studi di Cagliari',
    shortName: 'UniCa',
    emailDomains: ['unica.it'],
    city: 'Cagliari',
    type: 'statale',
    campuses: [
      {
        id: 'unica-saduchessa',
        name: 'Campus Sa Duchessa',
        city: 'Cagliari',
        address: 'Via Is Mirrionis 1, 09123 Cagliari',
      },
      {
        id: 'unica-monserrato',
        name: 'Cittadella Universitaria di Monserrato',
        city: 'Monserrato',
        address: 'S.S. 554 Bivio Sestu, 09042 Monserrato',
      },
      {
        id: 'unica-santignazio',
        name: "Campus Sant'Ignazio (Economia, Giurisprudenza, Scienze Politiche)",
        city: 'Cagliari',
        address: "Viale Sant'Ignazio 76, 09123 Cagliari",
      },
    ],
  },
  {
    id: 'unicam',
    name: 'Università degli Studi di Camerino',
    shortName: 'UniCam',
    emailDomains: ['unicam.it'],
    city: 'Camerino',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unicas',
    name: 'Università degli Studi di Cassino e del Lazio Meridionale',
    shortName: 'UniCas',
    emailDomains: ['unicas.it'],
    city: 'Cassino',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unict',
    name: 'Università degli Studi di Catania',
    shortName: 'UniCt',
    emailDomains: ['unict.it'],
    city: 'Catania',
    type: 'statale',
    campuses: [
      {
        id: 'unict-catania',
        name: 'Cittadella Universitaria - Catania',
        city: 'Catania',
        address: "Piazza dell'Università 2, 95131 Catania",
      },
      {
        id: 'unict-siracusa',
        name: 'Struttura Didattica Speciale di Architettura - Siracusa',
        city: 'Siracusa',
      },
      { id: 'unict-ragusa', name: 'Polo di Ragusa', city: 'Ragusa' },
    ],
  },
  {
    id: 'unicz',
    name: 'Università degli Studi di Catanzaro - Magna Graecia',
    shortName: 'UniCz',
    emailDomains: ['unicz.it'],
    city: 'Catanzaro',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unife',
    name: 'Università degli Studi di Ferrara',
    shortName: 'UniFe',
    emailDomains: ['unife.it'],
    city: 'Ferrara',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unifi',
    name: 'Università degli Studi di Firenze',
    shortName: 'UniFi',
    emailDomains: ['unifi.it', 'stud.unifi.it'],
    city: 'Firenze',
    type: 'statale',
    campuses: [
      {
        id: 'unifi-sanmarco',
        name: 'Sede centrale - Piazza San Marco',
        city: 'Firenze',
        address: 'Piazza San Marco 4, 50121 Firenze',
      },
      {
        id: 'unifi-novoli',
        name: 'Campus di Novoli (Economia, Giurisprudenza, Scienze Politiche)',
        city: 'Firenze',
        address: 'Via delle Pandette 32, 50127 Firenze',
      },
      { id: 'unifi-prato', name: 'Polo Universitario di Prato', city: 'Prato' },
      {
        id: 'unifi-sesto',
        name: 'Polo Scientifico di Sesto Fiorentino',
        city: 'Sesto Fiorentino',
        address: 'Viale delle Idee 26, 50019 Sesto Fiorentino',
      },
    ],
  },
  {
    id: 'unifg',
    name: 'Università degli Studi di Foggia',
    shortName: 'UniFg',
    emailDomains: ['unifg.it'],
    city: 'Foggia',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unige',
    name: 'Università degli Studi di Genova',
    shortName: 'UniGe',
    emailDomains: ['unige.it'],
    city: 'Genova',
    type: 'statale',
    campuses: [
      {
        id: 'unige-genova',
        name: 'Sede di Genova',
        city: 'Genova',
        address: 'Via Balbi 5, 16126 Genova',
      },
      { id: 'unige-savona', name: 'Campus di Savona', city: 'Savona' },
      { id: 'unige-imperia', name: 'Campus di Imperia', city: 'Imperia' },
      { id: 'unige-laspezia', name: 'Campus di La Spezia', city: 'La Spezia' },
    ],
  },
  {
    id: 'univaq',
    name: "Università degli Studi dell'Aquila",
    shortName: 'UnivAQ',
    emailDomains: ['univaq.it', 'student.univaq.it'],
    city: "L'Aquila",
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unimc',
    name: 'Università degli Studi di Macerata',
    shortName: 'UniMc',
    emailDomains: ['unimc.it'],
    city: 'Macerata',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unime',
    name: 'Università degli Studi di Messina',
    shortName: 'UniMe',
    emailDomains: ['unime.it'],
    city: 'Messina',
    type: 'statale',
    campuses: [
      {
        id: 'unime-papardo',
        name: 'Polo Papardo (Scienze, Ingegneria)',
        city: 'Messina',
        address: "Viale Ferdinando Stagno d'Alcontres 31, 98166 Messina",
      },
      {
        id: 'unime-annunziata',
        name: 'Polo Annunziata (Farmacia, Veterinaria)',
        city: 'Messina',
        address: 'Viale Giovanni Palatucci, 98168 Messina',
      },
      {
        id: 'unime-centro',
        name: 'Sede centrale - Piazza Pugliatti',
        city: 'Messina',
        address: 'Piazza Salvatore Pugliatti 1, 98122 Messina',
      },
    ],
  },
  {
    id: 'unimi',
    name: 'Università degli Studi di Milano',
    shortName: 'UniMi',
    emailDomains: ['unimi.it', 'studenti.unimi.it'],
    city: 'Milano',
    type: 'statale',
    campuses: [
      {
        id: 'unimi-cagranda',
        name: "Sede centrale - Ca' Granda",
        city: 'Milano',
        address: 'Via Festa del Perdono 7, 20122 Milano',
      },
      {
        id: 'unimi-cittastudi',
        name: 'Città Studi',
        city: 'Milano',
        address: 'Via Celoria 2, 20133 Milano',
      },
      {
        id: 'unimi-lodi',
        name: 'Polo di Lodi (Medicina Veterinaria)',
        city: 'Lodi',
        address: "Via dell'Università 6, 26900 Lodi",
      },
      { id: 'unimi-sesto', name: 'Polo di Sesto San Giovanni', city: 'Sesto San Giovanni' },
    ],
  },
  {
    id: 'unimib',
    name: 'Università degli Studi di Milano-Bicocca',
    shortName: 'UniMib',
    emailDomains: ['unimib.it', 'campus.unimib.it'],
    city: 'Milano',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unimore',
    name: 'Università degli Studi di Modena e Reggio Emilia',
    shortName: 'UniMore',
    emailDomains: ['unimore.it'],
    city: 'Modena',
    type: 'statale',
    campuses: [
      {
        id: 'unimore-modena',
        name: 'Sede di Modena',
        city: 'Modena',
        address: 'Via Università 4, 41121 Modena',
      },
      {
        id: 'unimore-reggio',
        name: 'Sede di Reggio Emilia',
        city: 'Reggio Emilia',
        address: 'Viale Antonio Allegri 9, 42121 Reggio Emilia',
      },
    ],
  },
  {
    id: 'uniparthenope',
    name: 'Università degli Studi di Napoli Parthenope',
    shortName: 'Parthenope',
    emailDomains: ['uniparthenope.it'],
    city: 'Napoli',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unina',
    name: 'Università degli Studi di Napoli Federico II',
    shortName: 'Federico II',
    emailDomains: ['unina.it', 'studenti.unina.it'],
    city: 'Napoli',
    type: 'statale',
    // NOTE: l'ateneo conta oltre 60 sedi sparse a Napoli e provincia — qui sono elencati solo
    // i poli principali e più riconoscibili, non l'elenco esaustivo.
    campuses: [
      {
        id: 'unina-centro-storico',
        name: 'Centro Storico (sede centrale)',
        city: 'Napoli',
        address: 'Corso Umberto I 40, 80138 Napoli',
      },
      {
        id: 'unina-fuorigrotta',
        name: 'Polo di Ingegneria - Fuorigrotta',
        city: 'Napoli',
        address: 'Piazzale Vincenzo Tecchio 80, 80125 Napoli',
      },
      {
        id: 'unina-policlinico',
        name: 'Policlinico (Scuola di Medicina)',
        city: 'Napoli',
        address: 'Via Sergio Pansini 5, 80131 Napoli',
      },
      {
        id: 'unina-portici',
        name: 'Polo di Agraria - Portici',
        city: 'Portici',
        address: 'Via Università 100, 80055 Portici',
      },
      {
        id: 'unina-quartieri-spagnoli',
        name: 'Polo di Architettura - Quartieri Spagnoli',
        city: 'Napoli',
      },
    ],
  },
  {
    id: 'unipd',
    name: 'Università degli Studi di Padova',
    shortName: 'UniPd',
    emailDomains: ['unipd.it', 'studenti.unipd.it'],
    city: 'Padova',
    type: 'statale',
    campuses: [
      {
        id: 'unipd-padova',
        name: 'Sede di Padova',
        city: 'Padova',
        address: 'Via VIII Febbraio 2, 35122 Padova',
      },
      {
        id: 'unipd-rovigo',
        name: 'Sede di Rovigo',
        city: 'Rovigo',
        address: 'Viale Porta Adige 45, 45100 Rovigo',
      },
      { id: 'unipd-treviso', name: 'Sede di Treviso', city: 'Treviso' },
      { id: 'unipd-vicenza', name: 'Sede di Vicenza', city: 'Vicenza' },
      {
        id: 'unipd-legnaro',
        name: 'Polo di Agraria - Legnaro',
        city: 'Legnaro',
        address: "Via dell'Università 16, 35020 Legnaro",
      },
    ],
  },
  {
    id: 'unipa',
    name: 'Università degli Studi di Palermo',
    shortName: 'UniPa',
    emailDomains: ['unipa.it', 'community.unipa.it'],
    city: 'Palermo',
    type: 'statale',
    campuses: [
      {
        id: 'unipa-palermo',
        name: 'Cittadella Universitaria - Palermo',
        city: 'Palermo',
        address: 'Viale delle Scienze, 90128 Palermo',
      },
      {
        id: 'unipa-trapani',
        name: 'Polo Territoriale di Trapani',
        city: 'Trapani',
        address: 'Lungomare Dante Alighieri 2, 91016 Trapani',
      },
      {
        id: 'unipa-agrigento',
        name: 'Polo Territoriale di Agrigento',
        city: 'Agrigento',
        address: 'Via Ugo La Malfa 1, 92100 Agrigento',
      },
      {
        id: 'unipa-caltanissetta',
        name: 'Polo Territoriale di Caltanissetta',
        city: 'Caltanissetta',
      },
    ],
  },
  {
    id: 'unipr',
    name: 'Università degli Studi di Parma',
    shortName: 'UniPr',
    emailDomains: ['unipr.it'],
    city: 'Parma',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unipv',
    name: 'Università degli Studi di Pavia',
    shortName: 'UniPv',
    emailDomains: ['unipv.it'],
    city: 'Pavia',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unipg',
    name: 'Università degli Studi di Perugia',
    shortName: 'UniPg',
    emailDomains: ['unipg.it'],
    city: 'Perugia',
    type: 'statale',
    campuses: [
      {
        id: 'unipg-perugia',
        name: 'Sede di Perugia',
        city: 'Perugia',
        address: "Piazza dell'Università 1, 06121 Perugia",
      },
      {
        id: 'unipg-terni',
        name: 'Polo Scientifico Didattico di Terni',
        city: 'Terni',
        address: 'Strada di Pentima 4, 05100 Terni',
      },
    ],
  },
  {
    id: 'iusm',
    name: 'Università degli Studi di Roma "Foro Italico"',
    shortName: 'Foro Italico',
    emailDomains: ['uniroma4.it'],
    city: 'Roma',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'uniroma1',
    name: 'Università degli Studi di Roma "La Sapienza"',
    shortName: 'Sapienza',
    emailDomains: ['uniroma1.it', 'studenti.uniroma1.it'],
    city: 'Roma',
    type: 'statale',
    campuses: [
      {
        id: 'uniroma1-citta-universitaria',
        name: 'Città Universitaria',
        city: 'Roma',
        address: 'Piazzale Aldo Moro 5, 00185 Roma',
      },
      { id: 'uniroma1-latina', name: 'Polo Universitario di Latina', city: 'Latina' },
      { id: 'uniroma1-rieti', name: 'Polo Universitario di Rieti', city: 'Rieti' },
    ],
  },
  {
    id: 'uniroma2',
    name: 'Università degli Studi di Roma "Tor Vergata"',
    shortName: 'Tor Vergata',
    emailDomains: ['uniroma2.it', 'students.uniroma2.eu'],
    city: 'Roma',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unisa',
    name: 'Università degli Studi di Salerno',
    shortName: 'UniSa',
    emailDomains: ['unisa.it', 'studenti.unisa.it'],
    city: 'Salerno',
    type: 'statale',
    campuses: [
      {
        id: 'unisa-fisciano',
        name: 'Campus di Fisciano (sede principale)',
        city: 'Fisciano',
        address: 'Via Giovanni Paolo II 132, 84084 Fisciano',
      },
      {
        id: 'unisa-baronissi',
        name: 'Campus di Baronissi (Medicina)',
        city: 'Baronissi',
        address: 'Via Salvador Allende, 84081 Baronissi',
      },
    ],
  },
  {
    id: 'uniss',
    name: 'Università degli Studi di Sassari',
    shortName: 'UniSs',
    emailDomains: ['uniss.it'],
    city: 'Sassari',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unite',
    name: 'Università degli Studi di Teramo',
    shortName: 'UniTe',
    emailDomains: ['unite.it'],
    city: 'Teramo',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unito',
    name: 'Università degli Studi di Torino',
    shortName: 'UniTo',
    emailDomains: ['unito.it', 'edu.unito.it'],
    city: 'Torino',
    type: 'statale',
    campuses: [
      {
        id: 'unito-torino',
        name: 'Sede di Torino',
        city: 'Torino',
        address: 'Via Giuseppe Verdi 8, 10124 Torino',
      },
      {
        id: 'unito-grugliasco',
        name: 'Campus di Grugliasco (Agraria e Medicina Veterinaria)',
        city: 'Grugliasco',
        address: 'Largo Paolo Braccini 2, 10095 Grugliasco',
      },
      {
        id: 'unito-savigliano',
        name: 'Polo di Savigliano',
        city: 'Savigliano',
        address: 'Via Giuseppe Garibaldi 6, 12038 Savigliano',
      },
    ],
  },
  {
    id: 'unitn',
    name: 'Università degli Studi di Trento',
    shortName: 'UniTn',
    emailDomains: ['unitn.it', 'studenti.unitn.it'],
    city: 'Trento',
    type: 'statale',
    campuses: [
      {
        id: 'unitn-trento',
        name: 'Sede di Trento',
        city: 'Trento',
        address: 'Via Belenzani 12, 38122 Trento',
      },
      {
        id: 'unitn-povo',
        name: 'Polo di Povo (Ingegneria, Scienze)',
        city: 'Trento',
        address: 'Via Sommarive 9, 38123 Povo',
      },
      {
        id: 'unitn-rovereto',
        name: 'Polo di Rovereto (Scienze Cognitive)',
        city: 'Rovereto',
        address: 'Corso Bettini 84, 38068 Rovereto',
      },
    ],
  },
  {
    id: 'units',
    name: 'Università degli Studi di Trieste',
    shortName: 'UniTs',
    emailDomains: ['units.it'],
    city: 'Trieste',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'uniud',
    name: 'Università degli Studi di Udine',
    shortName: 'UniUd',
    emailDomains: ['uniud.it'],
    city: 'Udine',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'univr',
    name: 'Università degli Studi di Verona',
    shortName: 'UniVr',
    emailDomains: ['univr.it'],
    city: 'Verona',
    type: 'statale',
    campuses: [
      {
        id: 'univr-veronetta',
        name: 'Polo Zanotto (Veronetta)',
        city: 'Verona',
        address: 'Via San Francesco 22, 37129 Verona',
      },
      {
        id: 'univr-borgoroma',
        name: 'Polo di Borgo Roma (Medicina e Scienze)',
        city: 'Verona',
        address: 'Piazzale Ludovico Antonio Scuro 10, 37134 Verona',
      },
      { id: 'univr-vicenza', name: 'Sede di Vicenza', city: 'Vicenza' },
    ],
  },
  {
    id: 'uninsubria',
    name: "Università degli Studi dell'Insubria",
    shortName: 'Insubria',
    emailDomains: ['uninsubria.it'],
    city: 'Varese',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unimol',
    name: 'Università degli Studi del Molise',
    shortName: 'UniMol',
    emailDomains: ['unimol.it', 'studenti.unimol.it'],
    city: 'Campobasso',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unipmn',
    name: 'Università degli Studi del Piemonte Orientale "Amedeo Avogadro"',
    shortName: 'UniPmn',
    emailDomains: ['uniupo.it'],
    city: 'Alessandria',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unisannio',
    name: 'Università degli Studi del Sannio',
    shortName: 'UniSannio',
    emailDomains: ['unisannio.it'],
    city: 'Benevento',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unicampania',
    name: 'Università degli Studi della Campania "Luigi Vanvitelli"',
    shortName: 'Vanvitelli',
    emailDomains: ['unicampania.it'],
    city: 'Caserta',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unibas',
    name: 'Università degli Studi della Basilicata',
    shortName: 'UniBas',
    emailDomains: ['unibas.it'],
    city: 'Potenza',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unitus',
    name: 'Università degli Studi della Tuscia',
    shortName: 'UniTus',
    emailDomains: ['unitus.it'],
    city: 'Viterbo',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unich',
    name: 'Università degli Studi "Gabriele D\'Annunzio" di Chieti e Pescara',
    shortName: 'UniCh',
    emailDomains: ['unich.it'],
    city: 'Chieti',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unior',
    name: 'Università degli Studi "L\'Orientale" di Napoli',
    shortName: 'UniOr',
    emailDomains: ['unior.it'],
    city: 'Napoli',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unirc',
    name: 'Università degli Studi Mediterranea di Reggio Calabria',
    shortName: 'UniRc',
    emailDomains: ['unirc.it'],
    city: 'Reggio Calabria',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'uniroma3',
    name: 'Università degli Studi Roma Tre',
    shortName: 'Roma Tre',
    emailDomains: ['uniroma3.it'],
    city: 'Roma',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unisalento',
    name: 'Università del Salento',
    shortName: 'UniSalento',
    emailDomains: ['unisalento.it'],
    city: 'Lecce',
    type: 'statale',
    campuses: [
      {
        id: 'unisalento-lecce',
        name: 'Polo Urbano - Lecce',
        city: 'Lecce',
        address: 'Piazza Tancredi 7, 73100 Lecce',
      },
      {
        id: 'unisalento-extraurbano',
        name: 'Polo Extraurbano - Campus Ecotekne',
        city: 'Lecce',
        address: 'Via Monteroni, 73100 Lecce',
      },
      {
        id: 'unisalento-brindisi',
        name: 'Polo di Brindisi (Ingegneria, Scienze Sociali)',
        city: 'Brindisi',
      },
    ],
  },
  {
    id: 'unical',
    name: 'Università della Calabria',
    shortName: 'UniCal',
    emailDomains: ['unical.it'],
    city: 'Rende',
    type: 'statale',
    campuses: [
      {
        id: 'unical-arcavacata',
        name: 'Campus di Arcavacata',
        city: 'Rende',
        address: 'Via Pietro Bucci, 87036 Arcavacata di Rende',
      },
      { id: 'unical-crotone', name: 'Polo di Crotone', city: 'Crotone' },
      { id: 'unical-vibovalentia', name: 'Polo di Vibo Valentia', city: 'Vibo Valentia' },
    ],
  },
  {
    id: 'unipi',
    name: 'Università di Pisa',
    shortName: 'UniPi',
    emailDomains: ['unipi.it', 'studenti.unipi.it'],
    city: 'Pisa',
    type: 'statale',
    campuses: [
      {
        id: 'unipi-pisa',
        name: 'Sede di Pisa',
        city: 'Pisa',
        address: 'Lungarno Antonio Pacinotti 43, 56126 Pisa',
      },
      {
        id: 'unipi-livorno',
        name: 'Polo Universitario Sistemi Logistici - Livorno',
        city: 'Livorno',
      },
      { id: 'unipi-lucca', name: 'Sede di Lucca (Monte San Quirico)', city: 'Lucca' },
    ],
  },
  {
    id: 'unisi',
    name: 'Università degli Studi di Siena',
    shortName: 'UniSi',
    emailDomains: ['unisi.it', 'student.unisi.it'],
    city: 'Siena',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'iuav',
    name: 'Università Iuav di Venezia',
    shortName: 'IUAV',
    emailDomains: ['iuav.it'],
    city: 'Venezia',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unistrapg',
    name: 'Università per Stranieri di Perugia',
    shortName: 'Stranieri Perugia',
    emailDomains: ['unistrapg.it'],
    city: 'Perugia',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unistrasi',
    name: 'Università per Stranieri di Siena',
    shortName: 'Stranieri Siena',
    emailDomains: ['unistrasi.it'],
    city: 'Siena',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'isuf',
    name: 'Istituto Italiano di Scienze Umane di Firenze',
    shortName: 'ISUF',
    emailDomains: [],
    city: 'Firenze',
    type: 'statale',
    campuses: [],
  },
  {
    id: 'unibo-proprietary',
    name: 'Università degli Studi di Bologna',
    shortName: 'UniBo',
    emailDomains: ['unibo.it', 'studio.unibo.it'],
    city: 'Bologna',
    type: 'statale',
    campuses: [],
  },

  // Private Universities
  {
    id: 'gssi',
    name: 'Gran Sasso Science Institute',
    shortName: 'GSSI',
    emailDomains: ['gssi.it'],
    city: "L'Aquila",
    type: 'privata',
    campuses: [],
  },
  {
    id: 'humanitas',
    name: 'Humanitas University',
    shortName: 'Humanitas',
    emailDomains: ['humanitas-u.it'],
    city: 'Milano',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unibz',
    name: 'Libera Università di Bolzano',
    shortName: 'UniBz',
    emailDomains: ['unibz.it'],
    city: 'Bolzano',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'iulm',
    name: 'Libera Università di Lingue e Comunicazione (IULM) di Milano',
    shortName: 'IULM',
    emailDomains: ['iulm.it'],
    city: 'Milano',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'lumsa',
    name: 'Libera Università Maria SS. Assunta (LUMSA) di Roma',
    shortName: 'LUMSA',
    emailDomains: ['lumsa.it'],
    city: 'Roma',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'lum',
    name: 'Libera Università Mediterranea "Giuseppe Degennaro"',
    shortName: 'LUM',
    emailDomains: ['lum.it'],
    city: 'Casamassima',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unikore',
    name: 'Libera Università della Sicilia Centrale "Kore" di Enna',
    shortName: 'Kore Enna',
    emailDomains: ['unikore.it'],
    city: 'Enna',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unisr',
    name: 'Vita-Salute San Raffaele di Milano',
    shortName: 'San Raffaele',
    emailDomains: ['unisr.it'],
    city: 'Milano',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unilink',
    name: 'Link Campus University di Roma',
    shortName: 'Link Campus',
    emailDomains: ['unilink.it'],
    city: 'Roma',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'luiss',
    name: 'LUISS Guido Carli di Roma',
    shortName: 'LUISS',
    emailDomains: ['luiss.it'],
    city: 'Roma',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unicamillus',
    name: 'Saint Camillus International University of Health',
    shortName: 'UniCamillus',
    emailDomains: ['unicamillus.org'],
    city: 'Roma',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'liuc',
    name: 'Università "Carlo Cattaneo" (LIUC)',
    shortName: 'LIUC',
    emailDomains: ['liuc.it'],
    city: 'Castellanza',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unicampus',
    name: 'Università Campus Bio-Medico di Roma',
    shortName: 'Campus Bio-Medico',
    emailDomains: ['unicampus.it'],
    city: 'Roma',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unicatt',
    name: 'Università Cattolica del Sacro Cuore',
    shortName: 'Cattolica',
    emailDomains: ['unicatt.it'],
    city: 'Milano',
    type: 'privata',
    campuses: [
      {
        id: 'unicatt-milano',
        name: 'Sede di Milano',
        city: 'Milano',
        address: 'Largo Agostino Gemelli 1, 20123 Milano',
      },
      { id: 'unicatt-roma', name: 'Sede di Roma', city: 'Roma' },
      {
        id: 'unicatt-brescia',
        name: 'Sede di Brescia',
        city: 'Brescia',
        address: 'Via Trieste 17, 25121 Brescia',
      },
      {
        id: 'unicatt-piacenza',
        name: 'Sede di Piacenza-Cremona',
        city: 'Piacenza',
        address: 'Via Emilia Parmense 84, 29122 Piacenza',
      },
      { id: 'unicatt-campobasso', name: 'Sede di Campobasso', city: 'Campobasso' },
    ],
  },
  {
    id: 'unibocconi',
    name: 'Università Commerciale Luigi Bocconi di Milano',
    shortName: 'Bocconi',
    emailDomains: ['unibocconi.it'],
    city: 'Milano',
    type: 'privata',
    campuses: [
      {
        id: 'unibocconi-sarfatti',
        name: 'Campus di via Sarfatti',
        city: 'Milano',
        address: 'Via Roberto Sarfatti 25, 20136 Milano',
      },
    ],
  },
  {
    id: 'unisob',
    name: 'Università degli Studi Suor Orsola Benincasa di Napoli',
    shortName: 'Suor Orsola',
    emailDomains: ['unisob.na.it'],
    city: 'Napoli',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'univda',
    name: "Università della Valle d'Aosta",
    shortName: 'UniVdA',
    emailDomains: ['univda.it'],
    city: 'Aosta',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unint',
    name: 'Università degli Studi Internazionali di Roma',
    shortName: 'UNINT',
    emailDomains: ['unint.eu'],
    city: 'Roma',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unisg',
    name: 'Università di Scienze Gastronomiche',
    shortName: 'UniSG',
    emailDomains: ['unisg.it'],
    city: 'Pollenzo',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unier',
    name: 'Università Europea di Roma',
    shortName: 'UnIER',
    emailDomains: ['unier.it'],
    city: 'Roma',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'unidante',
    name: 'Università per Stranieri "Dante Alighieri" di Reggio Calabria',
    shortName: 'Dante Alighieri',
    emailDomains: ['unistrada.it'],
    city: 'Reggio Calabria',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-lombardia',
    name: 'Istituto Superiore di Educazione Fisica della Lombardia',
    shortName: 'ISEF Lombardia',
    emailDomains: [],
    city: 'Milano',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-bologna',
    name: 'Istituto Superiore di Educazione Fisica di Bologna',
    shortName: 'ISEF Bologna',
    emailDomains: [],
    city: 'Bologna',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-firenze',
    name: 'Istituto Superiore di Educazione Fisica di Firenze',
    shortName: 'ISEF Firenze',
    emailDomains: [],
    city: 'Firenze',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-laquila',
    name: "Istituto Superiore di Educazione Fisica di L'Aquila",
    shortName: "ISEF L'Aquila",
    emailDomains: [],
    city: "L'Aquila",
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-milano',
    name: 'Istituto Superiore di Educazione Fisica di Milano',
    shortName: 'ISEF Milano',
    emailDomains: [],
    city: 'Milano',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-napoli',
    name: 'Istituto Superiore di Educazione Fisica di Napoli',
    shortName: 'ISEF Napoli',
    emailDomains: [],
    city: 'Napoli',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-palermo',
    name: 'Istituto Superiore di Educazione Fisica di Palermo',
    shortName: 'ISEF Palermo',
    emailDomains: [],
    city: 'Palermo',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-perugia',
    name: 'Istituto Superiore di Educazione Fisica di Perugia',
    shortName: 'ISEF Perugia',
    emailDomains: [],
    city: 'Perugia',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-torino',
    name: 'Istituto Superiore di Educazione Fisica di Torino',
    shortName: 'ISEF Torino',
    emailDomains: [],
    city: 'Torino',
    type: 'privata',
    campuses: [],
  },
  {
    id: 'isef-urbino',
    name: 'Istituto Superiore di Educazione Fisica di Urbino',
    shortName: 'ISEF Urbino',
    emailDomains: [],
    city: 'Urbino',
    type: 'privata',
    campuses: [],
  },

  // Telematic Universities
  {
    id: 'uniecampus',
    name: 'Università Telematica "e-Campus" di Novedrate',
    shortName: 'eCampus',
    emailDomains: ['uniecampus.it'],
    city: 'Novedrate',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unifortunato',
    name: 'Università Telematica "Giustino Fortunato" di Benevento',
    shortName: 'Fortunato',
    emailDomains: ['unifortunato.eu'],
    city: 'Benevento',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'iul',
    name: 'Università Telematica "Italian University Line" di Firenze',
    shortName: 'IUL',
    emailDomains: ['iuline.it'],
    city: 'Firenze',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unipegaso',
    name: 'Università Telematica "Pegaso" di Napoli',
    shortName: 'Pegaso',
    emailDomains: ['unipegaso.it'],
    city: 'Napoli',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unisanraffaele',
    name: 'Università Telematica "San Raffaele" di Roma',
    shortName: 'San Raffaele Roma',
    emailDomains: ['unisanraffaele.gnomon.it'],
    city: 'Roma',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unimarconi',
    name: 'Università Telematica Guglielmo Marconi di Roma',
    shortName: 'Marconi',
    emailDomains: ['unimarconi.it'],
    city: 'Roma',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'uninettuno',
    name: 'Università Telematica Internazionale UNINETTUNO di Roma',
    shortName: 'UNINETTUNO',
    emailDomains: ['uninettunouniversity.net'],
    city: 'Roma',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unicusano',
    name: 'Università Telematica Niccolò Cusano di Roma',
    shortName: 'Cusano',
    emailDomains: ['unicusano.it'],
    city: 'Roma',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unidav',
    name: 'Università Telematica Non Statale "Leonardo da Vinci"',
    shortName: 'Da Vinci',
    emailDomains: ['unidav.it'],
    city: 'Torrevecchia Teatina',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unitelma',
    name: 'Università Telematica Unitelma Sapienza di Roma',
    shortName: 'Unitelma',
    emailDomains: ['unitelma.it'],
    city: 'Roma',
    type: 'telematica',
    campuses: [],
  },
  {
    id: 'unimercatorum',
    name: 'Universitas Telematica Mercatorum di Roma',
    shortName: 'Mercatorum',
    emailDomains: ['unimercatorum.it'],
    city: 'Roma',
    type: 'telematica',
    campuses: [],
  },
];
